version: 2.1
workflows:
  test-deploy:
    jobs:
      - test
  nightly-workflow:
    triggers: 
      - schedule:
          cron: "58 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test

    
jobs:
  test:
    docker:
      - image: cimg/node:23.8.0
    steps:
      - checkout
      - run: 
          name: Install dep
          command: npm install
      - run:
          name: Unit tests
          command: npm run test
      - run:
          name: Check version
          command: npm --version

    
  
