version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node@7.1.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - attach_workspace:
          at: /app
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync /app/build s3://$AWS_S3_BUCKET --delete
      - run:
          name: Invalidate CloudFront Cache
          command: |
            aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths "/*"

workflows:
  deploy-app:
    jobs:
      - build
      - deploy:
          requires:
            - build
